--- 
-  hosts: all 
   become: yes
   tasks: 
    - name: "I want to install ubuntu webserver"
      apt: 
        name: "{{myubuntuwebservers}}"
        state: present
      when: 
         ansible_os_family == "Debian"   
    
    - name: "I want to install linux webserver"
      yum: 
        name: "{{mylinuxwebservers}}"
        state: present 
      when:      
        ansible_os_family == "RedHat"
