--- 
-  hosts: all 
   become: yes
   tasks: 
    - name: "I want to install ubuntu webserver"
      apt: 
        name: "{{myubuntuwebservers}}"
        state: present
      when: 
         ansible_os_family == "Debian"   
      register: myresult   
    
    - name: "I want to install linux webserver"
      yum: 
        name: "{{mylinuxwebservers}}"
        state: present 
      when:      
        ansible_os_family == "RedHat"

    - name: "I want to display results"
      debug: 
        msg: "{{myresult}}"

    - name: "I want to creat file in ubuntu"
      file: 
        path: /home/ubuntu/jay
        state: touch
      when: 
         ansible_os_family == "Debian"

    - name: "I want to creat file in linux"
      file:
        path: /home/harsh/bharat
        state: touch  
      when:      
        ansible_os_family == "RedHat"  